formatter: markdown table

version: ">= 0.16.0"

sections:
  show:
    - requirements
    - inputs
    - outputs

output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: required

settings:
  anchor: false
  color: false
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
